apiVersion: v1
kind: Service
metadata:
    name: "cardata-fc4b"
    labels:
        app: "cardata-fc4b"
spec:
    type: LoadBalancer
    ports:
    - port: 12345
      targetPort: 12345
      protocol: TCP
      name: http
    selector:
        app: "cardata-fc4b"