# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch.
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build".
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: qpetraroia.azurecr.io/go-web-app:${{ github.sha }}
      
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          file: dockerfile.curl
          context: .
          push: true
          tags: qpetraroia.azurecr.io/curl:${{ github.sha }}
          
      # set cluster context
      - uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: CarData
          resource-group: EVAddOns
    
      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/deployment.yml
          images: |
            ${{ secrets.CONTAINER_REGISTRY }}.azurecr.io/go-web-app:${{ github.sha }}
            ${{ secrets.CONTAINER_REGISTRY }}.azurecr.io/curl:${{ github.sha }}
            
